# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8607b42abb673b8cfd0aeb9f1193061456dcbefe6d60440c611d93aa0c79508845448f6d299cef31f686fc69e95345fbf842fdf47e9b46e6ea5cbdeb91e71d5a

test:
  secret_key_base: 0e9582196c1870988e78b6aa0ed668efc8f6f3ccb93373f6e90a806c0915d7baf7f8791fbe5f1fc28178c8ac0908c3f3ceb2e813e7401b723a42d5c18ffb4209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
